name: 'C++ CI'

env:
  PROJECT_NAME: "hw1"
  BUILD_PATH: "build"


on:
  push:
    paths:
      - '$PROJECT_NAME/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libgtest-dev libgmock-dev -y
      - run: mkdir $BUILD_PATH && cd $BUILD_PATH
      - run: cmake -S ../ -B .
      - run: cmake --build .
      - run: ctest
