name: 'C++ CI'

env:
  PROJECT_NAME: hw1
  BUILD_PATH: build


on:
  push:
    paths:
      - hw1/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install clang lld libgtest-dev libgmock-dev -y
      - name: Configure
        run: |
          mkdir -p $BUILD_PATH
          cmake -S./ -B./$BUILD_PATH -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_CC_COMPILER=/usr/bin/clang
      - name: Build
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          cmake --build .
      - name: Test
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          ctest
