name: 'C++ CI'

env:
  PROJECT_NAME: hw1
  BUILD_PATH: build


on:
  push:
    paths:
      - hw1/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libgtest-dev libgmock-dev -y
      - run: pwd
      - run: cmake -S . -B $BUILD_PATH
      - run: cmake --build $BUILD_PATH
      - run: ls
      - run: cd $BUILD_PATH
      - run: pwd
      - run: ctest
