name: 'C++ CI'

env:
  PROJECT_NAME: hw1
  BUILD_PATH: build


on:
  push:
    paths:
      - hw1/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v2
        run: |
          sudo apt-get update && sudo apt-get install libgtest-dev libgmock-dev -y
      - name: Configure
        uses: actions/checkout@v2
        run: |
          mkdir -p $BUILD_PATH
          cmake -S./ -B./$BUILD_PATH -DCMAKE_BUILD_TYPE=Release
      - name: Build
        uses: actions/checkout@v2
        working-directory: ./$BUILD_PATH
        run: |
          pwd
          cmake --build .
      - name: Test
        uses: actions/checkout@v2
        working-directory: ./$BUILD_PATH
        run: |
          pwd
          ctest
